version: "3.8"

services:
  db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=wtasker
      - POSTGRES_PASSWORD=wtasker
      - POSTGRES_DB=wtasker
    ports:
      - "5434:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data: